### ISSUE TITLE
"ValueError: no signature found for builtin <method 'set_alpha' of 'pygame.Surface' objects>"

### ISSUE THREAD

**Issue by Professor-Woody** [lionel42/pygame-matplotlib-backend#1]
Fresh install of Python 3.10, matplotlib, pygame, and this backend on a Windows-10 machine, received a set of errors when executing the following in IDLE:

`import pygame
import matplotlib
matplotlib.use('module://pygame_matplotlib.backend_pygame')
import matplotlib.pyplot as plt`

![image](https://user-images.githubusercontent.com/90181549/143766816-cad3bb76-6e5d-4760-bb5e-0048413b3a52.png)

Thought it would be worth mentioning

**Comment by lionel42** [comment]
Thanks for reporting,
I will make the library compatible with python 3.10, should not take just one day

**Comment by lionel42** [comment]
Last version has been uploaded to pypi.
Please let me know if it works on your side as well.
